version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-hello"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hncfg34cq5x9"
s3_prefix = "sam-hello"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
